### ISSUE TITLE
NullReferenceException when an account has no stocks

### ISSUE THREAD

**Issue by sixhills** [jonathanmadeley/hl-api-client-net#1]
First, may I thank you enormously for providing this library as my web-scraping skills aren't up to the task of navigating a two-stage login process and this will be very useful as a means of automating a daily record of my investment position.

I'm an absolute novice at C# and Visual Studio, although I'm reasonably competent in other languages.  Using your sample program, I've successfully logged in to Hargreaves Lansdown and listed stocks held in the first of my accounts.  But for historical reasons, I have a second account that holds no stocks.  The program gets as far as printing:

- Account: Stocks & Shares ISA 2 - formerly Mini
        Current Value: 0.00
        Total Share Value: 0.00
        Cash Held on Account: 0.00
  Stocks & Funds

and then crashes on the line "var rows = body.Descendants("tr").ToArray();" in AccountOperations.cs with "System.NullReferenceException: Object reference not set to an instance of an object".

I suspect there's a simple fix to check for an empty account, so I thought I'd report it before trying to fix it myself.  If you'd prefer me to submit a PR, I'm very happy to do so but it will take some time to familiarise myself with C# syntax.

**Comment by jonathanmadeley** [comment]
Hi @sixhills,

Thanks for getting in touch - I've just resolved the problem and pushed a new version (1.1.0). Feel free to contact me directly if you need any help with tracking to a spreadsheet, I have a project setup to do almost the identical thing.

Kind regards,
Jonathan.

**Comment by sixhills** [comment]
Hi @jonathanmadeley,

Wow, that was quick!  Many thanks for the fix, which I'm happy to confirm works perfectly.

Kind regards, Mike.
